# Generated by Django 2.1.3 on 2018-11-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyClass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('house_number', models.SmallIntegerField(max_length=1000)),
                ('apartment_number', models.SmallIntegerField(max_length=1000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyClass.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyClass.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('person', models.ManyToManyField(to='MyClass.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type_number', models.IntegerField(choices=[(1, 'domowy'), (2, 'służbowy'), (3, 'inny')])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyClass.Person')),
            ],
        ),
    ]
