# Generated by Django 2.1.3 on 2018-11-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyClass', '0004_auto_20181128_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='person_addres',
            new_name='person_adress',
        ),
    ]
