# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClass', '0005_auto_20181128_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(1, 'domowy'), (2, 'służbowy'), (3, 'inny')], default=1),
        ),
        migrations.AlterField(
            model_name='adress',
            name='apartment_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='adress',
            name='house_number',
            field=models.SmallIntegerField(),
        ),
    ]
