# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClass', '0006_auto_20181202_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=64),
        ),
    ]
