# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-03 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyClass', '0007_auto_20181202_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='person',
            new_name='person_email',
        ),
    ]
